# Generated by Django 3.2.6 on 2021-09-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Close'), ('E', 'Estimation')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, default=12, max_length=20, null=True)),
            ],
        ),
    ]
